# Generated by Django 4.1.13 on 2025-03-28 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Invoice',
            new_name='UploadedFile',
        ),
    ]
